import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {useTrail, animated} from "react-spring";
import React from "react";

const Trail = ({ children }) => {
  const items = React.Children.toArray(children)
  const trail = useTrail(items.length, {
    config: { mass: 5, tension: 2000, friction: 200 },
    opacity: 1,
    x: 0,
    height: 110,
    from: { opacity: 0, x: 20, height: 0 },
    delay: 300
  })

  return (
      <>
        {trail.map(({ height, ...style }, index) => (
            <animated.span key={index} style={style}>
              <animated.span style={{ height }}>{items[index]}</animated.span>
            </animated.span>
        ))}
      </>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}>
            <Trail>
              <span>Welcome </span>
              <span>to </span>
              <a href="https://nextjs.org">Next.js!</a>
            </Trail>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

        <div className={styles.grid}>
          <Link href="/react-spring/use-spring">
            <a className={styles.card}>
              <h2>React Spring &rarr;</h2>
              <p>useSpring()</p>
            </a>
          </Link>

          <Link href="/react-spring/parallax">
            <a className={styles.card}>
              <h2>React Spring &rarr;</h2>
              <p>Parallax</p>
            </a>
          </Link>

          <Link href="/gsap/reveal">
            <a className={styles.card}>
              <h2>Gsap &rarr;</h2>
              <p>Reveal effect</p>
            </a>
          </Link>


          <Link href="/gsap/scroll-trigger">
            <a className={styles.card}>
              <h2>Gsap &rarr;</h2>
              <p>ScrollTrigger example</p>
            </a>
          </Link>

          <Link href="/gsap/scroll-slider">
            <a className={styles.card}>
              <h2>Gsap &rarr;</h2>
              <p>ScrollSlider example</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
